/**
 * MasterscripFiles
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterscripFiles);
  }
}(this, function(expect, MasterscripFiles) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterscripFiles.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('masterscripFilePathsGet', function() {
      it('should call masterscripFilePathsGet successfully', function(done) {
        //uncomment below and update the code to test masterscripFilePathsGet
        //instance.masterscripFilePathsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('masterscripV1FilePathsGet', function() {
      it('should call masterscripV1FilePathsGet successfully', function(done) {
        //uncomment below and update the code to test masterscripV1FilePathsGet
        //instance.masterscripV1FilePathsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('masterscripV2FilePathsGet', function() {
      it('should call masterscripV2FilePathsGet successfully', function(done) {
        //uncomment below and update the code to test masterscripV2FilePathsGet
        //instance.masterscripV2FilePathsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('masterscripV4FilePathsGet', function() {
      it('should call masterscripV4FilePathsGet successfully', function(done) {
        //uncomment below and update the code to test masterscripV4FilePathsGet
        //instance.masterscripV4FilePathsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
