/**
 * MasterscripFiles
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* Default service.
* @module org.wso2.client.api.MasterscripFiles/DefaultApi
* @version 1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:org.wso2.client.api.MasterscripFiles/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the masterscripFilePathsGet operation.
     * @callback module:org.wso2.client.api.MasterscripFiles/DefaultApi~masterscripFilePathsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:org.wso2.client.api.MasterscripFiles/DefaultApi~masterscripFilePathsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    masterscripFilePathsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/masterscrip/file-paths', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the masterscripV1FilePathsGet operation.
     * @callback module:org.wso2.client.api.MasterscripFiles/DefaultApi~masterscripV1FilePathsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Use this endpoint to get ScripMaster Files with Headers
     * @param {module:org.wso2.client.api.MasterscripFiles/DefaultApi~masterscripV1FilePathsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    masterscripV1FilePathsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/masterscrip/v1/file-paths', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the masterscripV2FilePathsGet operation.
     * @callback module:org.wso2.client.api.MasterscripFiles/DefaultApi~masterscripV2FilePathsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * ScripMaster Files with Surveillance message 
     * @param {module:org.wso2.client.api.MasterscripFiles/DefaultApi~masterscripV2FilePathsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    masterscripV2FilePathsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/masterscrip/v2/file-paths', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the masterscripV4FilePathsGet operation.
     * @callback module:org.wso2.client.api.MasterscripFiles/DefaultApi~masterscripV4FilePathsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:org.wso2.client.api.MasterscripFiles/DefaultApi~masterscripV4FilePathsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    masterscripV4FilePathsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/masterscrip/v4/file-paths', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
